language: python

python:
    - "2.5"
    - "2.6"
    - "2.7"
    - "3.1"
    - "3.2"

install:
    - pip install -U -r requirements.pip --use-mirrors
    - pip install -U -r requirements-test.pip --use-mirrors
    - if [[ $TRAVIS_PYTHON_VERSION == '2.5' ]]; then pip install --use-mirrors unittest2; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi

script:
    # pep8 only 2.7
    - nosetests -I test_pep8.py
    - python setup.py install

notifications:
    email:
        on_success: change
        on_failure: always
