language: python
python:
    - "2.5"
    - "2.6"
    - "2.7"
    - "3.1"
    - "3.2"

install: "pip install -r requirements.pip --use-mirrors"

script: nosetests

notifications:
    email:
        on_success: change
        on_failure: change
